### ISSUE TITLE
About this project function

### ISSUE THREAD

**Issue by ylm3721** [mirceamt/HandwritingRecognition#1]
Hi,

Can the project  recognition the number(0-9) and English charcter (A-Z,a-z)?How about the recognize  precision? @mirceamt 

My e-mail :401058614@qq.com

**Comment by mirceamt** [comment]
Hi,

Sorry, I think I missed your email. The recognition works for digits as
well as for English characters. Precision is about 77% but that is because
there are lots of characters that look the same. (Eg. 0, O, o, or 1, i, I,
l, etc.) If we take this into consideration the precision is about 95%.
Also, I used some heuristics to determine what character is being written
like holding a dictionary in memory of all the English words, as well as
other heuristics.
The project cannot be run yet because I did not upload the trained model on
github but if you are interested in it tell me and I can help you with that.

Best regards,
Mircea
